[package]
name = "main-project"
version = "0.1.0"
edition = "2024"

[dependencies]
# ---- GUI ----
iced = "0.12"

# ---- Core file operations ----
walkdir = "2"          # recursive file walking
rfd = "0.15.4"
dirs-next = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"